### ISSUE TITLE
OverflowError: value must fit in 1 byte

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_RA8875#10]
Tested with latest stable CircuitPython and got this error:
```
Traceback (most recent call last):
  File "code.py", line 34, in <module>
  File "/lib/adafruit_ra8875/ra8875.py", line 588, in fill
  File "/lib/adafruit_ra8875/ra8875.py", line 812, in _rect_helper
  File "/lib/adafruit_ra8875/ra8875.py", line 190, in write_reg
  File "/lib/adafruit_ra8875/ra8875.py", line 212, in write_data
  File "/lib/adafruit_ra8875/ra8875.py", line 212, in write_data
OverflowError: value must fit in 1 byte(s)
```

**Comment by makermelissa** [comment]
I need to go through the code and fix this where necessary for each of the drawing functions.
