### ISSUE TITLE
TypeError when running simpletest on Raspberry Pi

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_RA8875#12]
This is the first time I've run it on the Raspberry Pi and it works mostly, but was a little laggy (SPI bus speed maybe) and output this error at the end:
```
Traceback (most recent call last):
  File "ra8875_simpletest.py", line 66, in <module>
    display.txt_write("Player Score: " + str(testvar))
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_ra8875/ra8875.py", line 475, in txt_write
    self._write_data(char, True)
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_ra8875/ra8875.py", line 225, in _write_data
    spi.write(data if raw else bytearray([data & 0xFF]))  # pylint: disable=no-member
  File "/home/pi/.local/lib/python3.7/site-packages/busio.py", line 170, in write
    return self._spi.write(buf, start, end)
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_blinka/microcontroller/generic_linux/spi.py", line 61, in write
    self._spi.writebytes2(buf[start:end])
TypeError: Non-Int/Long value in arguments: b6687160.
```

**Comment by makermelissa** [comment]
I think I have a fix for this. I just want to test on a feather first.
